### ISSUE TITLE
请问这个与phprpc的区别？

### ISSUE THREAD

**Issue by kaneg** [andot/hprose#11]
马哥，那个phprpc貌似也是你做的，膜拜啊，几乎把常用的语言都实现了，在python等动态语言里使用起来真的太简单了。请问这个hprose与phprpc有什么区别？是升级版还是全新的？是不是建议放弃phprpc，改用hprose？谢了。

**Comment by andot** [comment]
hprose 跟 phprpc 都是跨语言的 RPC 库，使用方式上也类似，所以从 phprpc 过渡到 hprose 没什么困难。但是 hprose 是全新设计并实现的，对强类型语言支持更好，比 phprpc 的运行效率也高（php版本需要安装 php-cpp 扩展效率才会高）。另外，phprpc 中内置的加密传输虽然在加密数据上有一定作用，但是却也可能会让 DDOS 攻击变得更有效（因为密钥交换请求比较消耗服务器资源，如果有人恶意不断的发起密钥交换请求，那服务器可能就不能正常工作了），因此在 hprose 中取消了这个功能。hprose 在很多的服务细节控制上做的比 phprpc 也好很多，更容易扩展。比如可以很轻松的通过 hprose 提供的 Filter 机制来实现自己的加密解密，压缩传输，甚至可以跟 jsonRPC 服务通讯。phprpc 从 2009 年之后就已经不在更新了。所以推荐使用 hprose。

**Comment by kaneg** [comment]
谢谢你的解答。那我就准备试试hprose，以后在使用过程中什么问题再向你请教。
