### ISSUE TITLE
Request support for unix socket

### ISSUE THREAD

**Issue by ejemba** [andot/hprose#12]
Unix Socket Domain as transport layer would be a killer feature in my case , particularly in Golang if possible. Thank you.

**Comment by andot** [comment]
It has been already implemented.
https://github.com/hprose/hprose-go

**Comment by ejemba** [comment]
@andot I already saw there is a hprose-go implementation and a TcpServer/Client , but I actually talk about Unix Socket Domain implementation, in particular in Golang. 
Perhaps i did not see it in the link you provide me.

**Comment by andot** [comment]
Unix Socket Domain implementation is here:
https://github.com/hprose/hprose-go/blob/master/hprose/unix_service.go
https://github.com/hprose/hprose-go/blob/master/hprose/unix_client.go

**Comment by ejemba** [comment]
@andot thank you 
I had shamelessly "only" look at your documentation not the source.
So this is wonderfull. Perhaps just an example in the documentation may be helpfull.
